# Generated by Django 3.2.3 on 2021-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('measure', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
